version: 0.2

env:
  secrets-manager:
   DOCKERHUB_USERNAME: "/dockerhub/credentials:username"
   DOCKERHUB_PASSWORD: "/dockerhub/credentials:password"

phases:
  pre_build:
    commands:
    - echo Loggin into Docker Hub..
    - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
    - docker --version
  build:
    commands:
     - echo Build started on `date`
     - echo Building the Docker image..
     - docker build . -t $IMAGE_REPO_NAME
     - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $IMAGE_REPO_NAME:$IMAGE_TAG
     - echo "we will run sometest"
     - grep -Fq "Hello World" app.js
  post_build:
    commands:
     - echo Build completed on `date`
     - echo Pushing the Docker image..
     - docker push $IMAGE_REPO_NAME:$IMAGE_TAG
     - echo Writing image definitions file...
     - printf '[{"name":"ContainerWebApp","imageUri":"%s"}]' $IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json